
DROP TABLE IF EXISTS #UNIV;
SELECT SUBMISSION.docID
		--,SUBMISSION.dateFile
		--,SUBMISSION.periodEnd
		,YEAR(SUBMISSION.dateFile) * 100 + MONTH(SUBMISSION.dateFile) AS FYEARMONTH
		,SUBMISSION.secCode
		,SUBMISSION.filerName
		,SUBMISSION.docDescription
		,SUM(CASE WHEN SI.docId IS NOT NULL THEN 1 ELSE 0 END) AS N
		,SUM(CASE WHEN SI.HoldingEntity = 'ReportingCompany' THEN 1 ELSE 0 END) AS N_REPORTING

		,SUM(CASE WHEN SI.HoldingEntity = 'LargestHoldingCompany' THEN 1 ELSE 0 END) AS N_LARGEST
		,SUM(CASE WHEN SI.HoldingEntity = 'LargestHoldingCompany' AND SI.HoldingEntityName IS NOT NULL THEN 1 ELSE 0 END) AS N_LARGEST_NAME

		,SUM(CASE WHEN SI.HoldingEntity = 'SecondLargestHoldingCompany' THEN 1 ELSE 0 END) AS N_SECOND
		,SUM(CASE WHEN SI.HoldingEntity = 'SecondLargestHoldingCompany' AND SI.HoldingEntityName IS NOT NULL THEN 1 ELSE 0 END) AS N_SECOND_NAME
		--,
		--,SI.HoldingEntityName
INTO #UNIV
FROM EDINET..DocumentMetadata AS SUBMISSION
	LEFT JOIN EDINET..SpecifiedInvestment AS SI
		ON SI.docId = SUBMISSION.docID
WHERE 1 = 1
	-- —L‰¿ØŒ”•ñ‘
	AND SUBMISSION.formCode IN ('030000', '030001')
	AND SUBMISSION.ordinanceCode = '010'
	--AND SUBMISSION.DOCID = 'S1007TAK' -- 16/3Šú‚ÌMS&AD
	--AND SUBMISSION.filerName LIKE 'MS&AD%'
GROUP BY SUBMISSION.dateFile, SUBMISSION.docID, SUBMISSION.secCode ,SUBMISSION.filerName, SUBMISSION.docDescription
ORDER BY SUBMISSION.dateFile, SUBMISSION.docID

SELECT FYEARMONTH
		--,dateFile
		,COUNT(*) AS N_DOC
		,SUM(CASE WHEN N > 0 THEN 1 ELSE 0 END) AS N_DOC_SI
		,SUM(CASE WHEN N_REPORTING > 0 THEN 1 ELSE 0 END) AS N_DOC_SI_REPORTING

		,SUM(CASE WHEN N_LARGEST > 0 THEN 1 ELSE 0 END) AS N_DOC_SI_LARGEST
		,SUM(CASE WHEN N_LARGEST_NAME > 0 THEN 1 ELSE 0 END) AS N_DOC_SI_LARGEST_NAME

		,SUM(CASE WHEN N_SECOND > 0 THEN 1 ELSE 0 END) AS N_DOC_SI_SECOND
		,SUM(CASE WHEN N_SECOND_NAME > 0 THEN 1 ELSE 0 END) AS N_DOC_SI_SECOND_NAME

FROM #UNIV
GROUP BY FYEARMONTH
ORDER BY FYEARMONTH
--SELECT DISTINCT SI.HoldingEntity
--FROM EDINET..SpecifiedInvestment AS SI

--SELECT *
--FROM EDINET..SpecifiedInvestment AS SI
--WHERE SI.DOCID = 'S100G4B9' -- MS&AD‚Ì2019

--SELECT * FROM #UNIV AS UNIV WHERE UNIV.N_LARGEST > 0 AND UNIV.N_LARGEST_NAME = 0
SELECT * FROM #UNIV AS UNIV WHERE UNIV.N_LARGEST = UNIV.N_LARGEST_NAME and UNIV.N_LARGEST_NAME > 0

